name: records
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.4
  json_annotation: ^4.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutterfire_ui: ^0.4.0
  get: ^4.6.1
  google_sign_in: ^5.2.1
  fluwx_no_pay: ^3.8.2
  flutter_quill: ^4.1.1
  window_manager: ^0.2.1
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  msix: ^3.5.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
