name: records
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.4
  json_annotation: ^4.4.0
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_database: ^9.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutterfire_ui: ^0.4.0
  get: ^4.6.1
  google_sign_in: ^5.2.1
  fluwx_no_pay: ^3.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
