// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmQ4HgqliUOE1NmdUBpKs1tQro9BXOpq4',
    appId: '1:390629804982:web:99cd6e4d8b35c1c2678f17',
    messagingSenderId: '390629804982',
    projectId: 'records-5e0b8',
    authDomain: 'records-5e0b8.firebaseapp.com',
    databaseURL:
        'https://records-5e0b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'records-5e0b8.appspot.com',
    measurementId: 'G-J31RR3K03M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6NQslchdN3HkspiygtKPqXqvRm6Z5Pp8',
    appId: '1:390629804982:android:d3db08095a16fe3c678f17',
    messagingSenderId: '390629804982',
    projectId: 'records-5e0b8',
    databaseURL:
        'https://records-5e0b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'records-5e0b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYqyn_aas5-q1vWs9nRWMdQQG60d9OyXo',
    appId: '1:390629804982:ios:42816b900f5287b5678f17',
    messagingSenderId: '390629804982',
    projectId: 'records-5e0b8',
    databaseURL:
        'https://records-5e0b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'records-5e0b8.appspot.com',
    iosClientId:
        '390629804982-cqroqvpt8i3cr5eslbld8hps2n9aesm0.apps.googleusercontent.com',
    iosBundleId: 'com.zwp.app',
  );
}
